env:
  RUBY_VERSION: 2.7.1
  
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rubocop-linting:
    name: rubocop-linting
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with: 
          ruby-version: ${ { 2.7.1 } }
      - name: Install Rubocop For Rails
        run: gem install rubocop-rails
      - name: Check code
        run: rubocop

